import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Listing, ListingImage, SaleRecord } from '@prisma/client';
import { readFile } from 'fs/promises';
import { join } from 'path';
import PDFDocument = require('pdfkit');
import QRCode = require('qrcode');
import { decodeLocalUploadToken, resolveLocalObjectPath } from '../uploads/local-upload-url';

const sharp: typeof import('sharp').default = require('sharp');

type SellerForReport = { name: string; phone: string; email?: string | null };
type SellerForInfoSheet = {
  id: string;
  name: string;
  phone: string;
  email: string | null;
  region: string | null;
  role: string;
  isPhoneVerified: boolean;
  createdAt: Date;
};

const COLORS = {
  accent: '#a13a00',
  mutedClay: '#c2521b',
  accentSubtle: '#ffdbce',
  borderClay: '#dfc0b5',
  textPrimary: '#191c1d',
  textSecondary: '#57423a',
  surface: '#ffffff',
  base: '#f8f9fa',
};

@Injectable()
export class PdfService {
  private logoBuffer?: Promise<Buffer>;
  private iconBuffer?: Promise<Buffer>;

  constructor(private readonly configService: ConfigService) {}

  generateSaleReport(params: {
    listing: Listing;
    saleRecord: SaleRecord;
    seller: SellerForReport;
  }): Promise<Buffer> {
    const doc = new PDFDocument({ size: 'A4', margin: 48, bufferPages: false });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));

    const finished = new Promise<Buffer>((resolve, reject) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);
    });

    const { listing, saleRecord, seller } = params;
    const generatedAt = new Date();

    doc
      .font('Helvetica-Bold')
      .fontSize(24)
      .fillColor('#a13a00')
      .text('AcreX', 48, 42)
      .fillColor('#191c1d')
      .fontSize(18)
      .text('Sale Confirmation Report', 48, 78)
      .font('Helvetica')
      .fontSize(9)
      .fillColor('#596373')
      .text(`Generated on ${this.formatDateTime(generatedAt)}`, 360, 50, { width: 185, align: 'right' });

    this.rule(doc, 116);
    this.sectionTitle(doc, 'Listing', 142);
    this.row(doc, 'Title / reference', listing.title, 164);
    this.row(doc, 'Location', [listing.region, listing.district].filter(Boolean).join(', '), 184);
    this.row(doc, 'Size', `${this.formatNumber(listing.sizeSqm)} sqm`, 204);
    this.row(doc, 'Listing ID', listing.id, 224);

    this.sectionTitle(doc, 'Sale Details', 268);
    this.row(doc, 'Sale date', this.formatDate(saleRecord.saleDate), 290);
    this.row(doc, 'Sale price', this.formatMoney(saleRecord.salePrice.toString(), listing.currency), 310);
    this.row(doc, 'Payment method', saleRecord.paymentMethod, 330);
    this.row(doc, 'Document reference', saleRecord.documentReference ?? '-', 350);

    this.sectionTitle(doc, 'Buyer', 394);
    this.row(doc, 'Name', saleRecord.buyerName, 416);
    this.row(doc, 'Phone', saleRecord.buyerPhone, 436);
    this.row(doc, 'Email', saleRecord.buyerEmail ?? '-', 456);

    this.sectionTitle(doc, 'Seller', 500);
    this.row(doc, 'Name', seller.name, 522);
    this.row(doc, 'Phone', seller.phone, 542);
    this.row(doc, 'Email', seller.email ?? '-', 562);

    this.rule(doc, 690);
    doc
      .font('Helvetica')
      .fontSize(9)
      .fillColor('#596373')
      .text(
        'This confirmation record was generated by AcreX. It is not a legal title deed, government document, or substitute for independent legal verification.',
        48,
        708,
        { width: 500 },
      )
      .text(`Report ID: ${saleRecord.id}`, 48, 748, { width: 500 });

    doc.end();
    return finished;
  }

  async generateListingInfoSheet(params: {
    listing: Listing;
    images: ListingImage[];
    seller: SellerForInfoSheet;
  }): Promise<Buffer> {
    const doc = new PDFDocument({ size: 'A4', margin: 42, bufferPages: false });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));

    const finished = new Promise<Buffer>((resolve, reject) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);
    });

    const { listing, seller } = params;
    const images = await this.loadListingImages(params.images.slice(0, 4));
    const listingUrl = this.buildListingUrl(listing.id);
    const qrBuffer = await QRCode.toBuffer(listingUrl, { width: 200, margin: 1 });

    await this.drawInfoSheetPageOne(doc, listing, params.images.length, images);
    await this.drawSellerAndFooter(doc, listing, seller, qrBuffer, listingUrl);

    doc.end();
    return finished;
  }

  private async drawInfoSheetPageOne(
    doc: PDFKit.PDFDocument,
    listing: Listing,
    totalImageCount: number,
    images: Buffer[],
  ) {
    doc.rect(0, 0, 595.28, 841.89).fill(COLORS.surface);
    doc.rect(0, 0, 595.28, 8).fill(COLORS.accent);

    const logo = await this.getLogoBuffer();
    doc.image(logo, 42, 26, { width: 118 });
    doc
      .font('Helvetica')
      .fontSize(8)
      .fillColor(COLORS.textSecondary)
      .text(`Listing ID: ${listing.id}`, 342, 30, { width: 210, align: 'right' });

    doc
      .font('Helvetica-Bold')
      .fontSize(22)
      .fillColor(COLORS.textPrimary)
      .text(this.valueOrDash(listing.title), 42, 80, { width: 510, height: 56 });

    doc
      .font('Helvetica')
      .fontSize(9)
      .fillColor(COLORS.textSecondary)
      .text(
        `${this.locationLabel(listing)} | ${this.formatMoney(
          listing.price.toString(),
          listing.currency,
        )} | ${this.formatNumber(listing.sizeSqm)} m2`,
        42,
        122,
        { width: 510 },
      );

    this.drawPhotoGrid(doc, images, 42, 148);

    this.sectionHeader(doc, 'Listing details', 386);
    this.drawDetailsTable(doc, listing, totalImageCount, 412);

    this.sectionHeader(doc, 'Description', 642);
    doc
      .font('Helvetica')
      .fontSize(9)
      .lineGap(2)
      .fillColor(COLORS.textSecondary)
      .text(this.valueOrDash(listing.description), 42, 668, { width: 510, height: 96 });
  }

  private drawPhotoGrid(doc: PDFKit.PDFDocument, images: Buffer[], x: number, y: number) {
    const gap = 8;
    const cellW = 251;
    const cellH = 106;
    const positions =
      images.length <= 1
        ? [{ x, y, width: 510, height: 220 }]
        : [
            { x, y, width: cellW, height: cellH },
            { x: x + cellW + gap, y, width: cellW, height: cellH },
            { x, y: y + cellH + gap, width: cellW, height: cellH },
            { x: x + cellW + gap, y: y + cellH + gap, width: cellW, height: cellH },
          ];

    if (images.length === 0) {
      this.drawImagePlaceholder(doc, x, y, 510, 220);
      return;
    }

    positions.slice(0, Math.min(images.length, 4)).forEach((box, index) => {
      doc.save();
      doc.roundedRect(box.x, box.y, box.width, box.height, 8).clip();
      doc.image(images[index], box.x, box.y, { width: box.width, height: box.height });
      doc.restore();
      doc.roundedRect(box.x, box.y, box.width, box.height, 8).lineWidth(0.75).strokeColor(COLORS.borderClay).stroke();
    });

    if (images.length === 2) {
      doc
        .roundedRect(x, y + cellH + gap, 510, cellH, 8)
        .fillAndStroke(COLORS.base, COLORS.borderClay);
      doc
        .font('Helvetica')
        .fontSize(10)
        .fillColor(COLORS.textSecondary)
        .text('Additional photos available on the live listing.', x, y + cellH + 52, {
          width: 510,
          align: 'center',
        });
    }
  }

  private drawImagePlaceholder(
    doc: PDFKit.PDFDocument,
    x: number,
    y: number,
    width: number,
    height: number,
  ) {
    doc.roundedRect(x, y, width, height, 8).fillAndStroke(COLORS.base, COLORS.borderClay);
    doc
      .font('Helvetica-Bold')
      .fontSize(13)
      .fillColor(COLORS.textSecondary)
      .text('Photo unavailable', x, y + height / 2 - 8, { width, align: 'center' });
  }

  private drawDetailsTable(
    doc: PDFKit.PDFDocument,
    listing: Listing,
    totalImageCount: number,
    y: number,
  ) {
    const rows = [
      ['Reference', listing.id],
      ['Region', this.valueOrDash(listing.region)],
      ['District', this.valueOrDash(listing.district)],
      ['Size', `${this.formatNumber(listing.sizeSqm)} m2`],
      ['Price', this.formatMoney(listing.price.toString(), listing.currency)],
      ['Price per m2', this.formatPricePerSqm(listing)],
      ['Status', listing.status.replaceAll('_', ' ')],
      ['Listed date', this.formatDate(listing.createdAt)],
      ['Photo count', String(totalImageCount)],
      [
        'Coordinates',
        listing.latitude != null && listing.longitude != null
          ? `${listing.latitude.toFixed(5)}, ${listing.longitude.toFixed(5)}`
          : '-',
      ],
    ];
    const rowH = 21;
    const labelW = 132;

    rows.forEach(([label, value], index) => {
      const rowY = y + index * rowH;
      doc
        .rect(42, rowY, 510, rowH)
        .fill(index % 2 === 0 ? COLORS.base : COLORS.surface)
        .strokeColor(COLORS.borderClay)
        .lineWidth(0.35)
        .stroke();
      doc
        .font('Helvetica-Bold')
        .fontSize(9)
        .fillColor(COLORS.textPrimary)
        .text(label, 54, rowY + 6, { width: labelW });
      doc
        .font('Helvetica')
        .fontSize(9)
        .fillColor(COLORS.textSecondary)
        .text(value, 54 + labelW, rowY + 6, { width: 350 });
    });
  }

  private async drawSellerAndFooter(
    doc: PDFKit.PDFDocument,
    listing: Listing,
    seller: SellerForInfoSheet,
    qrBuffer: Buffer,
    listingUrl: string,
  ) {
    doc.addPage({ size: 'A4', margin: 42 });
    doc.rect(0, 0, 595.28, 841.89).fill(COLORS.surface);
    doc.rect(0, 0, 595.28, 8).fill(COLORS.accent);

    this.sectionHeader(doc, 'Seller contact', 48);
    doc.roundedRect(42, 78, 320, 156, 8).fillAndStroke(COLORS.base, COLORS.borderClay);
    this.compactRow(doc, 'Name', seller.name, 98);
    this.compactRow(doc, 'Phone', seller.phone, 122);
    this.compactRow(doc, 'Email', seller.email ?? '-', 146);
    this.compactRow(doc, 'Region', seller.region ?? '-', 170);
    this.compactRow(doc, 'Verified', seller.isPhoneVerified ? 'Phone verified' : 'Phone not verified', 194);
    this.compactRow(doc, 'Member since', this.formatMonthYear(seller.createdAt), 218);

    doc.image(qrBuffer, 428, 76, { width: 100 });
    doc
      .font('Helvetica')
      .fontSize(8)
      .fillColor(COLORS.textSecondary)
      .text('Scan to view live listing', 398, 184, { width: 160, align: 'center' })
      .text(listingUrl, 374, 198, { width: 210, align: 'center' });

    this.sectionHeader(doc, 'Listing overview', 272);
    doc
      .font('Helvetica')
      .fontSize(9)
      .lineGap(3)
      .fillColor(COLORS.textSecondary)
      .text(
        `This AcreX info sheet summarizes the public listing for ${this.valueOrDash(
          listing.title,
        )}. The listing is currently marked ${listing.status.replaceAll(
          '_',
          ' ',
        )} and was first listed on ${this.formatDate(listing.createdAt)}. The stated location is ${this.locationLabel(
          listing,
        )}; coordinates are ${
          listing.latitude != null && listing.longitude != null
            ? `${listing.latitude.toFixed(5)}, ${listing.longitude.toFixed(5)}`
            : 'not provided'
        }.`,
        42,
        300,
        { width: 510 },
      );

    this.sectionHeader(doc, 'Suggested buyer checks', 392);
    this.bullet(doc, 'Confirm boundary markers and site access in person before committing funds.', 42, 420);
    this.bullet(doc, 'Ask the seller for current title, survey, transfer, and tax documentation.', 42, 444);
    this.bullet(doc, 'Use the QR code to confirm the latest price, status, photos, and seller details.', 42, 468);
    this.bullet(doc, 'AcreX can summarize listing information, but legal verification remains the buyer responsibility.', 42, 492);

    this.sectionHeader(doc, 'Included public data', 540);
    doc
      .font('Helvetica')
      .fontSize(9)
      .lineGap(3)
      .fillColor(COLORS.textSecondary)
      .text(
        'Included fields: listing reference, title, description, region, district, size, price, status, listed date, coordinates when available, public seller contact, and public listing photos. Verification document files are intentionally excluded from this public PDF.',
        42,
        568,
        { width: 510 },
      );

    const icon = await this.getIconBuffer();
    doc.opacity(0.08).image(icon, 430, 600, { width: 110 }).opacity(1);

    doc
      .moveTo(42, 704)
      .lineTo(552, 704)
      .lineWidth(0.75)
      .strokeColor(COLORS.borderClay)
      .stroke();
    doc
      .font('Helvetica')
      .fontSize(9)
      .fillColor(COLORS.textSecondary)
      .text(`Generated on ${this.formatDateTime(new Date())}`, 42, 724, { width: 240 })
      .text(`Listing ID: ${listing.id}`, 312, 724, { width: 240, align: 'right' })
      .text(
        'This AcreX listing sheet is for informational purposes only. It is not a legal title deed, government document, valuation, or substitute for independent legal verification.',
        42,
        752,
        { width: 510 },
      );
  }

  private sectionHeader(doc: PDFKit.PDFDocument, title: string, y: number) {
    doc
      .font('Helvetica-Bold')
      .fontSize(12)
      .fillColor(COLORS.mutedClay)
      .text(title, 42, y);
  }

  private compactRow(doc: PDFKit.PDFDocument, label: string, value: string, y: number) {
    doc
      .font('Helvetica-Bold')
      .fontSize(9)
      .fillColor(COLORS.textPrimary)
      .text(label, 62, y, { width: 72 })
      .font('Helvetica')
      .fillColor(COLORS.textSecondary)
      .text(this.valueOrDash(value), 140, y, { width: 190 });
  }

  private bullet(doc: PDFKit.PDFDocument, value: string, x: number, y: number) {
    doc.circle(x + 3, y + 4, 2).fill(COLORS.accent);
    doc
      .font('Helvetica')
      .fontSize(9)
      .fillColor(COLORS.textSecondary)
      .text(value, x + 16, y, { width: 488 });
  }

  private sectionTitle(doc: PDFKit.PDFDocument, title: string, y: number) {
    doc.font('Helvetica-Bold').fontSize(12).fillColor('#191c1d').text(title, 48, y);
  }

  private row(doc: PDFKit.PDFDocument, label: string, value: string, y: number) {
    doc
      .font('Helvetica')
      .fontSize(10)
      .fillColor('#596373')
      .text(label, 48, y, { width: 145 })
      .fillColor('#191c1d')
      .text(value, 205, y, { width: 340 });
  }

  private rule(doc: PDFKit.PDFDocument, y: number) {
    doc.moveTo(48, y).lineTo(547, y).lineWidth(0.75).strokeColor('#dfc0b5').stroke();
  }

  private formatMoney(value: string, currency: string) {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency,
      maximumFractionDigits: 0,
    }).format(Number(value));
  }

  private formatNumber(value: number) {
    return new Intl.NumberFormat('en-US').format(value);
  }

  private formatDate(date: Date) {
    return new Intl.DateTimeFormat('en-US', { dateStyle: 'medium' }).format(date);
  }

  private formatDateTime(date: Date) {
    return new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeStyle: 'short' }).format(date);
  }

  private formatMonthYear(date: Date) {
    return new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric' }).format(date);
  }

  private formatPricePerSqm(listing: Listing) {
    if (listing.sizeSqm <= 0) return '-';
    return this.formatMoney((Number(listing.price.toString()) / listing.sizeSqm).toString(), listing.currency);
  }

  private locationLabel(listing: Listing) {
    return [listing.region, listing.district].filter(Boolean).join(', ') || '-';
  }

  private valueOrDash(value?: string | null) {
    return value && value.trim() ? value : '-';
  }

  private buildListingUrl(id: string) {
    const origin = this.configService
      .getOrThrow<string>('CORS_ORIGIN')
      .split(',')
      .map((value) => value.trim())
      .find((value) => value && value !== '*');

    return `${origin?.replace(/\/$/, '') ?? 'http://localhost:3000'}/listings/${id}`;
  }

  private async loadListingImages(images: ListingImage[]) {
    const buffers: Buffer[] = [];
    for (const image of images) {
      try {
        buffers.push(await this.loadImageBuffer(image.url));
      } catch {
        // Missing or unsupported listing images should not block PDF generation.
      }
    }
    return buffers;
  }

  private async loadImageBuffer(url: string) {
    const localPath = this.localUploadPathFromUrl(url);
    if (localPath) return readFile(localPath);

    const response = await fetch(url);
    if (!response.ok) throw new Error(`Failed to fetch image: ${response.status}`);
    return Buffer.from(await response.arrayBuffer());
  }

  private localUploadPathFromUrl(url: string) {
    const marker = '/uploads/local/';
    const apiMarker = '/api/backend/uploads/local/';
    const markerIndex = url.includes(apiMarker) ? url.indexOf(apiMarker) + apiMarker.length : -1;
    const fallbackIndex = markerIndex === -1 && url.includes(marker) ? url.indexOf(marker) + marker.length : -1;
    const tokenStart = markerIndex !== -1 ? markerIndex : fallbackIndex;
    if (tokenStart === -1) return null;

    const token = url.slice(tokenStart).split(/[?#/]/)[0];
    return resolveLocalObjectPath(decodeLocalUploadToken(token));
  }

  private getLogoBuffer() {
    this.logoBuffer ??= this.rasterizeSvg(join(process.cwd(), '..', 'web', 'public', 'acrex-logo.svg'), 304);
    return this.logoBuffer;
  }

  private getIconBuffer() {
    this.iconBuffer ??= this.rasterizeSvg(join(process.cwd(), '..', 'web', 'public', 'acrex-icon.svg'), 168);
    return this.iconBuffer;
  }

  private async rasterizeSvg(path: string, width: number) {
    const svg = await readFile(path);
    return sharp(svg).resize({ width }).png().toBuffer();
  }
}
